export const IS_AUTHTHENTICATED = 'IS_AUTHTHENTICATED';
export const SET_USER = 'SET_USER';

export const SET_USER_ALL_CHATS_LIST = 'SET_USER_ALL_CHATS_LIST';
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';
export const SET_CHAT_LIST = 'SET_CHAT_LIST';
export const SET_CHATS = 'SET_CHATS';
export const SET_SEARCH_CHAT_BY_NAME = 'SET_SEARCH_CHAT_BY_NAME';
